feat: error codes
fuseio/fuseswap-service pull request #34
Opened 2021-05-15 18:44 UTC by mul53

2021-05-16 08:00 UTC, leonprou requested changes
Looks good. See the comments

2021-05-16 08:00 UTC, leonprou commented on src/services/swap.ts
> +    if (!currencyIn || !currencyOut || !parsedAmount || !pairs) throw new NoPoolLiquidityError()
Can you give an example of the error response? Would be cool to add an error example in the docs

2021-05-16 16:36 UTC, mul53 commented on docs/api.md
> +GET /pricechange
Okay i have done that

2021-05-18 09:19 UTC, leonprou approved these changes

2021-05-18 09:19 UTC, merged